controller_manager:
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    feixi_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    feixi_forward_position_controller:
      type: forward_command_controller/ForwardCommandController
